// GENERATED by `bun run brand:generate`. Hand-edits are overwritten and
// `bun run brand:check` fails on them.
//
// theme_color / background_color for server/routes/manifest.webmanifest.get.ts,
// resolved from DESIGN.md › Brand mark › Color roles `manifest-theme` and
// `manifest-ground` — see scripts/generate-brand-assets.ts.

export const BRAND_MANIFEST_COLORS = {
  themeColor: '#c74f2f',
  backgroundColor: '#fafaf9',
} as const
