// The email half of the brand pipeline — pure, so test/brand.test.ts can run it
// in workerd. `bun run brand:generate` resolves the `email-*` roles to hex in a
// browser (a Tailwind built-in like `stone-100` is oklch, and no email client
// reads oklch) and hands them here; the result is emails/theme.generated.css.
//
// It is generated rather than computed inside `bun run email:build` because
// building must work where there is no Chromium (the Workers Builds image).
// Generating once, committing the hex, and fingerprinting the inputs in
// brand.lock.json gives the same guarantee without the browser.

import type { BrandRole } from './brand-source'

/** Role → Tailwind color name, so `text-ink` and `bg-accent` read in templates. */
const EMAIL_COLORS = {
  'email-page': 'page',
  'email-card': 'card',
  'email-rule': 'rule',
  'email-ink': 'ink',
  'email-body': 'copy',
  'email-muted': 'muted',
  'email-accent': 'accent',
  'email-on-accent': 'on-accent',
  'email-bad': 'bad',
  'email-warn': 'warn',
  'email-good': 'good',
} as const satisfies Partial<Record<BrandRole, string>>

/**
 * What a stack ends in, after the brand's own first family. Email clients have
 * no webfonts to speak of and do not understand `ui-sans-serif` or `system-ui`,
 * so DESIGN.md's tail is replaced with names Outlook, Gmail and Apple Mail
 * actually resolve. The brand family still leads: it renders for anyone who has
 * it installed, and costs nothing for anyone who does not.
 */
const SAFE_SANS = `-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif`
const SAFE_MONO = `ui-monospace, Menlo, Consolas, monospace`

export interface EmailThemeInput {
  palette: Record<BrandRole, string>
  fonts: { sans: string; mono: string }
}

export function emailThemeCss({ palette, fonts }: EmailThemeInput): string {
  const colors = Object.entries(EMAIL_COLORS).map(
    ([role, name]) => `  --color-${name}: ${palette[role as keyof typeof EMAIL_COLORS]};`,
  )
  return `/* GENERATED by \`bun run brand:generate\` from DESIGN.md › Brand mark › Color roles.
 * Hand-edits are overwritten and \`bun run brand:check\` fails on them.
 *
 * Hex on purpose: email clients do not support CSS variables or oklch. */

@import '@maizzle/tailwindcss';

@theme {
${colors.join('\n')}
  --font-sans: '${fonts.sans}', ${SAFE_SANS};
  --font-mono: '${fonts.mono}', ${SAFE_MONO};
}
`
}
